### PR TITLE
copySubscriptionInformation - do not copy over a parent subscription

### PR DESCRIPTION
**Pull request by photodude**

### CODE REVIEW

**Comment by nikosdion** [comment]
You can't get into this situation under normal circumstances. Also the code to get $toProperties is wrong making this entire PR have no effect. That's why it "worked": it actually made no difference :)

**Comment by photodude** [comment]
I ran into this situation as an admin disabling a slave subscription, I think that is a possible situation under normal circumstances. the result was the parent subscription also got disabled, which is an undesirable behavior. 

The $toProperties code is wrong? I copied the code exactly as the $fromData and $properties variable lines are written, with just a change of variables for this new check.

**Comment by nikosdion** [comment]
Only a change made to a subscription with slaves (ergo a parent subscription) results in the propagation of its changes to the slaves. Therefore you're talking about a subscription who's both a parent and a slave. This means that someone screwed up.

As for the code, var_dump it and you'll understand.

**Comment by photodude** [comment]
I'm not talking about "a subscription who's both a parent and a slave." In testing I created a subscription on the front end with a single slave user (who is a different user). Then in the admin I set the slave to "enabled - no, payment status - new" saved and closed then ran integrations. The result was the parent subscription also being disabled.

I'll take a look at the var_dump.

**Comment by nikosdion** [comment]
Cannot reproduce following your instructions.

**Comment by photodude** [comment]
I'll see if I can come up with better replication instructions. I have also fixed the code to properly catch this issue. (I'm not sure why was I trying to look at array key's to make the check originally...)

**Pull request closed without merging**
