### PR TITLE
slave subs are not "valid" since they are not enabled

### PR DESCRIPTION
**Pull request by photodude**
add required processor_key as a random number, set state to completed, and enable the subscription.
consideration should be placed on possibly using the function copySubscriptionInformation in the future to ensure the slave is enabled and synced with the parent sub on creation.

### CODE REVIEW

**Comment by nikosdion** [comment]
While the processor_key is a valid point (and we also need to cater for a different processor), the rest of the changes you made are wrong. Let me give you an example.

Dr. Evil come to Austin Powers' site and creates two user accounts "drevil" and "minime". He goes into his subscription page, log in as "drevil" and fills in the add-on username "minime". Then he pays for the subscription with PayPal. Immediately he asks for a chargeback and PayPal being the Russian roulette it is grants it. The end result is that Austin Powers has no money in his pocket and Dr. Evil can enjoy his free subscription under the "minime" account. Not quite what you want.

I'm tracking this down. I have two competing theories. Filed under "fun stuff to do after the stroke of midnight"...

**Comment by photodude** [comment]
I would agree that scenario isn't what we'd want. I wonder, wouldn't that scenario cause a SubscriptionChange from the "canceled" subscription under "drevil" and would thus "expire" the slave sub under the "minime" account? or does paypal fail to send information back to the site indicating a "cancelled or failed payment" on chargeback?

**Comment by nikosdion** [comment]
Actually, the problem is in copySubscriptionInformation. The line `foreach ($properties as $k => $v)` should read `foreach ($properties as $k)`.

**Comment by photodude** [comment]
looks like the copySubscriptionInformation might not be called correctly, the Payment ID (processor_key) the state or Enabled status of the parent subscription isn't syncing up in the slave.

**Comment by nikosdion** [comment]
Yep. I see you implemented the changed I made in the development branch. Do you think your PR is ready for merging now?

**Comment by photodude** [comment]
It's in a better place than where it was, but I think there is still some work to be done to fully resolve this issue.

**Comment by nikosdion** [comment]
Ping me when you think it's ready

**Comment by photodude** [comment]
I'm not sure why, but the state and Enabled status of the parent subscription still isn't syncing up in the slave. Other than (the reason this PR was opened) this PR should be ready to merge.

**Comment by nikosdion** [comment]
I'm looking at the changes you made. It looks like a serious overkill. I have a few suspicions about what is going wrong. Since Akeeba Subs 5 (written on FOF 3) is practically complete, pending my tests against the payment processors, I think I'll not merge this PR. The slave subscriptions feature in AS5 seems to be working much better and far simpler.

**Comment by photodude** [comment]
ya there definitely is quite a bit there. Some of the "over kill" is directed at implementing something that would achieve the result that the AS5 does with just one function (findorfail). Others are to address some of the issues I've noticed while testing (slave users were not added to the akeebasubs_users table resulting in a SQL error, and slave subscriptions were duplicating when run integrations is initiated).

Considering the "broken" state of slave subscriptions in the 4.x branch and anticipating AS5 is nearing release with a simpler and "functioning" slave subs implementation, it's probably sixes whether to merge or not. 

I'm moving on to trying to setup and test against the AS5 version, but apparently my XAMPP set up hates me as it is failing the symlinks (php ../buildfiles/tools/link.php %CD%)  before I can even attempt the build. (might just be my novice developer experience)

FAILED SYMLINK : c:/xampp/ak/akeebasubs/build/bin
FAILED SYMLINK : c:/xampp/ak/akeebasubs/build/buildlang
FAILED SYMLINK : c:/xampp/ak/akeebasubs/build/phingext
FAILED SYMLINK : c:/xampp/ak/akeebasubs/build/tools
FAILED SYMLINK : c:/xampp/ak/akeebasubs/component/language/backend/en-GB
FAILED SYMLINK : c:/xampp/ak/akeebasubs/component/language/frontend/en-GB

**Comment by photodude** [comment]
I finally got a build for AS5 to test against.

I will concur that the "slave subs are not "valid" since they are not enabled" is resolved in AS5 along with the "slave subscription duplication on run integrations" issue

I will note that slave users are not added to akeebasubs_users table. but there is no longer a SQL error on editing a slave subscription for a user that is not in the akeebasubs_users table. (slave user not added to akeebasubs_users table on edit of a slave user subscription, may or may not be an issue)

clicking on the subscription level I got an error "Error LIB_FOF_MODEL_ERR_CANNOTLOCKNOTLOADEDRECORD" (is there a translation string missing here?) another possible missing translation (I couldn't find it in the translation files) COM_AKEEBASUBS_CUSTOMFIELD_ERR_AKEEBASUBS_LEVEL_ID_EMPTY

-editing a parent subscription dates in the admin side will sync the slave subscription.
-attempting to disable a parent subscription (set to payment - cancelled/rejected and enabled to no) resulted in a forced relogin and 403 error on admin login "View not found [name, type, prefix]: login, html, usersView" but both the parent and slave subscriptions were still disabled. (note: testing with a parent subscription for the admin user making the changes url is of the form [site]administrator/index.php?option=com_users&view=login&return=[hash])
-testing various subscription changes to the parent. slaves appear to sync on every save.
-admin is unable to remove a slave user by just leaving the slave user field blank

I'll see if I can do some more testing next week sometime.

**Comment by nikosdion** [comment]
You're right that slave subscribers do not get added to the #__akeebasubs_users table. This is perfectly normal since we don't have user-specific data to store such as address and business information.

Regarding the other messages:
* LIB_FOF_MODEL_ERR_CANNOTLOCKNOTLOADEDRECORD. This says that the record is locked (by another user). You got the untranslated string because FOF didn't install its language files. I was working on this last week.
* COM_AKEEBASUBS_CUSTOMFIELD_ERR_AKEEBASUBS_LEVEL_ID_EMPTY. How did you get this? This message gets generated when you try to save a custom field on a subscription which has no subscription level ID associated with it.

Regarding everything else:
* -editing a parent subscription dates in the admin side will sync the slave subscription. Yes, this is the intended behaviour. Otherwise it wouldn't be a perfect slave ;)
* attempting to disable a parent subscription (set to payment - cancelled/rejected and enabled to no) resulted in a forced relogin and 403 error on admin login. When you change the status of a subscription and if you are the owner of that subscription will attempt to log you out of the site and log you back in. Obviously on a real world site you won't do that for admin users and you'll not see that behaviour. Adding the code to guard against it caused a few strange issues so I'd rather live with this unlikely issue.
* -testing various subscription changes to the parent. slaves appear to sync on every save. They should :) The slavesubs plugin is tasked with copying all changes made to the subscription object to the slaves.
* -admin is unable to remove a slave user by just leaving the slave user field blank. Yes, this is expected. You'd have to delete the slave subscription first. This is necessary to be allowed to create slave subscriptions. Trust me, handling it otherwise creates a lot more problems. Since you can work around this in the back-end it's not a big deal.

**Comment by photodude** [comment]
Glad that you concur that my testing has verified that the behaviors you expected are as expected. 

"LIB_FOF_MODEL_ERR_CANNOTLOCKNOTLOADEDRECORD" error replication steps
1) do a global check in to insure no records are checked out
2) From the subscription click on a subscription level (not the subscription just the level)
the subscriptions levels view displays with the error at this point (past behavior opened the subscription level edit view)

As for the other error, "COM_AKEEBASUBS_CUSTOMFIELD_ERR_AKEEBASUBS_LEVEL_ID_EMPTY" I'll have to review all the different scenarios I tested. It might have been related to the unlikely "admin modifying a subscription for self"

more testing I found the following. 
-setting a slave subscription to new payment and enabled to no, then using 'run integrations' results in the parent subscription becoming disabled.  Seems like there is an unintended "reverse" sync happening in the copySubscriptionInformation function. I think a simple check to see if we should be modifying the row could resolve this. Either check that this is a slave "has a parent sub" so proceed to copy, or a check "has slave users" so do not copy. I'll see about putting together a patch today or later this week. 
-unable to re-enable a parent subscription that becomes disabled from a slave subscription being disabled. 
-admin is unable to remove a slave user by deleting the slave subscription then removing the slave user from the parent subscription by leaving the slave user field blank. The a slave subscription is recreated on run integrations. 
- when a price dropdown is an available custom option, the following error is given when an admin is creating a subscription (edit view opened) Warning: array_key_exists() expects parameter 2 to be array, null given in /administrator/components/com_akeebasubs/CustomField/Pricedropdown.php on line 34 (does not prevent creating the subscription)  likely due to there being no price in the fields when the admin edit screen first opens.
-possible missing translation string COM_AKEEBASUBS_LBL_SUBSCRIPTION_DELETED

**Comment by photodude** [comment]
A note on this AS4 issue, I've tracked down the issue to 2 items.
1. The copySubscriptionInformation wasn't saving data (proposed fix in PR)
2. The values being passed to copySubscriptionInformation are ending up as the same value.
(after line 434 the value of $from has changed; from the value set in line 433 to the value set for $to in line 434) I'm not sure why the value changed from one line to the next.

**Comment by nikosdion** [comment]
Ah, yes! You did pretty much the same fixes I did in AS 5. I wasn't sure if the mistakes I had fixed in AS 5 were part of AS 4 or stupid crap I did while refactoring the code.

**Comment by photodude** [comment]
I have gone back and forth on a number of things trying to find a solution. In the process I tried to bring some of your AS5 changes back to AS4 to see if that would resolve the "AS4 slavesubs is mostly broken". 

Still have the issue with the wrong values being passed to copySubscriptionInformation from line 433. I'm still not sure why the value changed from one line to the next.

**Comment by nikosdion** [comment]
Very soon you won't have to care. FOF3 and AS5 are almost ready.

**Comment by photodude** [comment]
I'm looking forward to it. I'll have to try to convince my team to move to AS 5 and adjust release dates as necessary.

**Pull request merged**
