### PR TITLE
Eliminate duplicated code for creating new slave subs.

### PR DESCRIPTION
**Pull request by photodude**
This change also fixes the issue with the parent sub not saving the Slave Sub IDs to the parent sub params in the database.

### CODE REVIEW

**Comment by nikosdion** [comment]
Why did you remove the check against user id 0? This is wrong! A user can provide an invalid username. This will make $user_id to be 0. If you try creating a subscription against user 0 you will get an error at best. I agree that the rest of the changes make sense, but please reinstate that check. It's a safeguard against bad user data. Remember, the usernames come from user input. You need to assume it's malicious or bad data unless positively proven otherwise.

**Comment by photodude** [comment]
I felt it was a duplicated code, as there is a check against user id 0 in the function "createSlaveSub" which would serve the same purpose. I can add it back if you feel it is still necessary and not just duplication.

**Comment by nikosdion** [comment]
I'd rather have the check in two places. It makes it easier to not screw up when I complete my planned refactoring :)

**Comment by photodude** [comment]
Sounds like a good plan. I have put the check back in.

**Pull request merged**
