### PR TITLE
Update RELEASENOTES.html

### PR DESCRIPTION
**Pull request by chivitli**
Wrong year I guess :-)

### CODE REVIEW

**Comment by nikosdion** [comment]
No, that date *is* correct. The support category was locked in January 2015.

**Comment by chivitli** [comment]
My mistake then since I saw you were still taking car of issues reported on Github without a proposed patch :)

**Comment by nikosdion** [comment]
Haha! If it's something obvious that comes with good instructions to reproduce and is indeed a bug –not just how I intended the software to behave– I will fix it. If anyone comes here asking for generic support they get no reply ;)

**Comment by chivitli** [comment]
Faie enough ;)

**Pull request closed without merging**
