### PR TITLE
PayPal update created on date after recurring payment

### PR DESCRIPTION
**Pull request by piotrmocko**

### CODE REVIEW

**Comment by nikosdion** [comment]
Thank you for fixing the recurring payment support in the PayPal integration!

**Comment by piotrmocko** [comment]
No problem. I am using recurring payments since a few months with my own
payment gateway and I need to get working PayPal.

I have some other changes in my code like:

- handle txn_type = subscr_cancel to save in database that subscription was
cancelled and there will be no more recurring payments. I store this data
in a new table where each row points to many subscription in Akeeba because
after each recurring payment there is a new subscription in Akeeba, but on
PayPal it is still the same subscription profile with constant ID. In this
table I save also cancellation date. This gives me information to show or
hide cancel button in user subscriptions list view. I also change
contact_flag to 0 to enable email notifications as subscription is expiring.

- recurring_index - in Akeeba subscriptions I store index of each recurring
payment to know order of them and in my new table I store the last index of
recurring payment.

- in PayPal plugin I use onValidateSubscriptionLength to change only the
time of first period of recurring subscription and all upcoming recurring
payments will be in period defined in level settings.

- common signup fee - if there are other levels i n the same level group
then you pay only once signup fee.

- disallow to buy level if user has active recurring level in the same
levelgroup

- show multiple levels in order form to select there which one you want

- use invoice ID instead of subscription ID to handle in easier way
multiple invoices for one subscription, for example when someone gets
refund and when it is a recurring payment. I have added some more changes
in invoice generation, but some of them are already in version 5.x

- save invoices PDF in separate folders fore each month-year

- handle fee_amount from PayPal to get better statistics about total income

- save PayPal account email in User profile table if different than Joomla
User to be able to find subscription by this other email.

- allow to buy as guest

You can check my cart at
https://www.perfect-web.co/order/43,44,45


---
Pozdrawiam,
 Piotr Moćko

2015-11-04 9:16 GMT+01:00 Nicholas K. Dionysopoulos <
notifications@github.com>:

**Comment by nikosdion** [comment]
There are some features I'm interested in having in Akeeba Subscriptions:

* common signup fee
* disallow to buy level if user has active recurring level in the same levelgroup
* show multiple levels in order form to select there which one you want
* save invoices PDF in separate folders fore each month-year

If you have time to do PRs against development I'd merge that code.

**Comment by piotrmocko** [comment]
I will try to make some PRs in near feature.


---
Pozdrawiam,
 Piotr Moćko

2015-11-04 10:23 GMT+01:00 Nicholas K. Dionysopoulos <
notifications@github.com>:

**Pull request merged**
