### PR TITLE
Add the pretty pictures for the customers

### PR DESCRIPTION
**Pull request by photodude**
We have the pictures, let's show them in this summary view. (like is done on all other views)

### CODE REVIEW

**Comment by nikosdion** [comment]
If you have 64x64px subscription level images the page looks like crap. The line is about 20px in height and there's this unsightly 64px image pushing the row height. Even worse if you're using odd sized images or larger (e.g. 256x256) images. You need to provide a height attribute to prevent this issue.

Moreover this should be an optional feature, enabled through the component's Options. On sites where there's a sidebar on the subscriptions page (most sites, including mine) there's not much room left. I prefer showing the useful invoice download button than the useless subscription level image.

**Comment by photodude** [comment]
The requested changes have been made. This PR is ready for merge consideration.

**Comment by nikosdion** [comment]
Sorry to be the ballbuster here, but did you try it with a very large image (e.g. 512x512px) as the source? You are only setting the table cell width here, not the img width. If Javascript is disabled or they're using a non-Bootstrap theme (at least without its magic responsive image manipulation) the image will either get cropped instead of scaled or push the table cell width depending on the CSS. Can you add a width attribute to the img element for good measure?

**Comment by photodude** [comment]
I can see your points, I have added a width attribute to the img element for good measure

**Pull request merged**
