### PR TITLE
Romanian VAT update

### PR DESCRIPTION
**Pull request by chivitli**
It seems Romania reduced VAT rate from 20% to 19% on 1st of January. Documents on EU portal are still not updated, but it can be seen for example at: http://www.capital.ro/reducerea-tva-la-19-eliminarea-supraaccizei-la-carburanti.html (in Romanian), or https://en.wikipedia.org/wiki/European_Union_value_added_tax#VAT_rates or when you check big shops in Romania: http://auchan.ro/auchan-redus-tva-la-19-la-produsele-nealimentare/ and http://www.f64.ro/lexar-sdxc-professional-2000x-card-128gb-uhs-ii-u3-clasa-10-cititor-carduri-sd-uhs-ii.html

### CODE REVIEW

**Comment by chivitli** [comment]
Here's the info on the website of the UK government: https://www.gov.uk/government/publications/vat-information-sheet-0217-changes-to-the-vat-rate-for-romania/vat-information-sheet-0217-changes-to-the-vat-rate-for-romania

UK HRMC sent an email today:

"Dear VAT MOSS user,
As you may be aware, the Romanian VAT rate decreased from 20% to 19% from 1 January 2017. We publicised this in VAT information sheet 02/17. Hungary have now informed us that they have a new reduced VAT rate for ‘internet access’ services of 18% which is valid from 1 January 2017. The standard VAT rate of all other kinds of telecommunication, broadcasting or electronic services remains at 27%."

**Comment by nikosdion** [comment]
Hello Marco,

I use the official VAT rates published by the European Union at https://ec.europa.eu/taxation_customs/sites/taxation/files/resources/documents/taxation/vat/how_vat_works/rates/vat_rates_en.xlsx

I re-read that very carefully today and I see that:
* Romanian VAT is still 20%
* The reduced Hungarian VAT rate does not seem to apply to service provision over the Internet but to ISP services (which are out of scope of Akeeba Subscriptions).

Nicholas K. Dionysopoulos • Director and Lead Developer
Akeeba Ltd 
51 Metochiou Str., Flat 303, 1101 Nicosia, Cyprus 
https://www.AkeebaBackup.com [https://www.akeebabackup.com/]
On 26/1/2017 13:34:46, Marko D <notifications@github.com> wrote:
Here's the info on the website of the UK government: https://www.gov.uk/government/publications/vat-information-sheet-0217-changes-to-the-vat-rate-for-romania/vat-information-sheet-0217-changes-to-the-vat-rate-for-romania [https://www.gov.uk/government/publications/vat-information-sheet-0217-changes-to-the-vat-rate-for-romania/vat-information-sheet-0217-changes-to-the-vat-rate-for-romania]
UK HRMC sent an email today:
"Dear VAT MOSS user,
As you may be aware, the Romanian VAT rate decreased from 20% to 19% from 1 January 2017. We publicised this in VAT information sheet 02/17. Hungary have now informed us that they have a new reduced VAT rate for ‘internet access’ services of 18% which is valid from 1 January 2017. The standard VAT rate of all other kinds of telecommunication, broadcasting or electronic services remains at 27%."

**Comment by chivitli** [comment]
Yeah, this document is my first point of reference as well. I guess they will update it eventually and then when we fill in the next return expect us to have applied the correct rate as of 1st of January... I think the same was when Greece changed its VAT rate last year. Actually, in the Belgian MOSS system they still had the old rate, but there was a message saying 'VAT was changed but our system hasn't been updated. Nevertheless, you should apply the correct rate, just enter it manually'.

For Hungarian VAT, I know, I just copied the full message.

Anyway, keep an eye on this, the reality seems to have changed, and EC will probably catch up at some point.

**Comment by chivitli** [comment]
The EU website at http://ec.europa.eu/taxation_customs/tic/public/vatRates shows the same, 19% for Romania. Full VAT history: http://ec.europa.eu/taxation_customs/tic/public/vatRates/history.html?msa=25

The xls and pdf they link on their homepage are not updated, but their database apparently is.

**Comment by chivitli** [comment]
Sorry, the first link about should be http://ec.europa.eu/taxation_customs/tic/public/vatRates/vatrates.html

**Comment by nikosdion** [comment]
I'll have to take your word for it since the server is off-line now :D I'll change the Romanian rate to 19%.

**Comment by chivitli** [comment]
Works ok for me the server? Did you click on the corrected link in the second email? http://ec.europa.eu/taxation_customs/tic/public/vatRates/vatrates.html and http://ec.europa.eu/taxation_customs/tic/public/vatRates/history.html?msa=25

**Pull request closed without merging**
