### PR TITLE
Update signup.js

### PR DESCRIPTION
**Pull request by marr-th**

### CODE REVIEW

**Comment by nikosdion** [comment]
I see many obviously wrong changes made there. The telltale ones was that you changed the capitalisation of a view and that you are using jQuery instead of window.jQuery. What are you trying to do with your changes? I don't see the reason for most of them and those I can understand what you're doing are just wrong?

**Comment by marr-th** [comment]
I'm sorry ,

change after I noticed that the file has been updated with respect to which I changed.

This serves to write the vat number without any prefix for countries outside the European Union.
for example: if I elegy Spain (prefix was set to "ES") and if after elegy, the United States did not update prefix

The important modification and if it is functional is this part of the code
-
-					Object.keys(akeebasubs_eu_configuration).forEach(function(key){
-						if (key == country)
+var k = country in akeebasubs_eu_configuration
+					
+						if (k)
 						{
 							$('#vatfields').css('display', 'block');
 							//$('#vatcountry').css('display','inline-block');
 
-							var ccode = akeebasubs_eu_configuration[key][1];
+							var ccode = akeebasubs_eu_configuration[country][1];
 							$('#vatcountry').text(ccode);
 
-						}
-					});
+						}else{
+							$('#vatcountry').text('');
+							}
+

**Comment by nikosdion** [comment]
I still don't understand what you are saying :( "Elegy" is a kind of a poem, typically written to honour the dead.

If I GUESS correctly you are tying to enter a VAT number for non-EU countries? Can you post a video showing me what you are trying to do to help me understand you?

**Comment by marr-th** [comment]
https://github.com/akeeba/akeebasubs/pull/176

I am sorry for my Inglés (google)

**Pull request closed without merging**
