### PR TITLE
Add Password Checks from user Component params

### PR DESCRIPTION
**Pull request by Skullbock**
This PR adds the same checks that Joomla\CMS\Form\Rule\PasswordRule implements for the normal com_users component.

### CODE REVIEW

**Comment by nikosdion** [comment]
The FOF Forms package [was deprecated in 2017](https://github.com/akeeba/fof/commit/7cf5b6f3122598fe89bba00cc1c5e1e3319d0c2e) and [removed in the upcoming FOF 4](https://github.com/akeeba/fof/commit/d801f8eb6c0e0f1f37d9e5d7237de50c15ec4281). As a result I won't integrate an PRs regarding the Forms package. Sorry.

You can always create your custom field. However, I would very strongly recommend upgrading your components to Blade (or plain PHP) templates in the near future. When Joomla 4 goes stable we expect that only FOF 4 will have work done in it to be compatible with both Joomla! 3.10 and 4.0. If you're using FOF Forms you are stuck with Joomla! 3. In fact, the main reason we removed the FOF Forms is that there is no reasonable way to have them render correctly under Joomla 4.

**Comment by Skullbock** [comment]
Hi Nicholas, thanks for the notice.
I just don't see how this impact my PR (maybe i'm just rusty with fof?)

The Subscribe Model of Akeeba Subscriptions doesn't rely on forms, and validates the data using "rules" which are not attached to FOFForm in any way i can see from the code.

Am i missing something?

**Comment by nikosdion** [comment]
I think I misread your PR. Sorry.

Regarding this PR, I would add a master switch to this feature. Enforcing password rules is great when you have people resetting their password but it's a bit problematic when you have them sitting on the fence, trying to pay you money. The more difficult you make it for them to subscribe the less likely it is they will. My approach is to let them use shit passwords and move them towards enabling two step verification. It is more secure and provides less friction.

Can you please add a master switch for that feature?

**Comment by Skullbock** [comment]
No problem!
Sure, would you add a simple "use the same params as the users component params" or replicate the params of the users component into aksubs?

**Comment by nikosdion** [comment]
Just a master switch "Apply Joomla! password strength requirements" default off. If that's enabled use Joomla's parameters for password strength.

**Comment by Skullbock** [comment]
Done!

**Pull request merged**
