### PR TITLE
VAT rate was displaying regardless of show VAT setting

### PR DESCRIPTION
**Pull request by photodude**
- Fixes the VAT display option introduced in 4.2

### CODE REVIEW

**Comment by nikosdion** [comment]
I could swear I had added that code... I must be getting old.

**Comment by photodude** [comment]
It's all good. Do you think it's worth doing a 4.2.2 release at this point?

**Comment by nikosdion** [comment]
Not really. I'm going to release version 5 sometime in late June. The 4.x branch is deprecated.

**Comment by photodude** [comment]
I can see that. I was just thinking a bug fix release of the 4.x branch might be nice while we are waiting for the initial release of the 5.x branch.

**Comment by nikosdion** [comment]
It's a developers' product, you can produce a dev release anytime you like without me having to publish a release on a deprecated branch (which won't happen exactly because it is a deprecated branch).

**Pull request merged**
